# Scenario:
# You are building the backend for an e-commerce platform. You receive a raw list of sales data. Each transaction contains a product, its category, the price per item, and the quantity sold.Your Goal:Write a Python function named aggregate_sales(transactions) that processes this data and returns a structured, nested dictionary containing:The total revenue generated by each category (Revenue = price × quantity).A unique list of products sold within that category.

# Input Data:
# pythontransactions = [
#     {"product": "Laptop", "category": "Electronics", "price": 1000, "quantity": 2},
#     {"product": "Jeans", "category": "Apparel", "price": 50, "quantity": 5},
#     {"product": "Smartphone", "category": "Electronics", "price": 800, "quantity": 1},
#     {"product": "T-Shirt", "category": "Apparel", "price": 20, "quantity": 10},
#     {"product": "Laptop", "category": "Electronics", "price": 1000, "quantity": 1},
#     {"product": "Book", "category": "Media", "price": 15, "quantity": 4}
# ]

# Expected Output:
# Your function should return exactly this dictionary structure (note that "Laptop" only appears once in the Electronics list because it should track unique products):python{
#     "Electronics": {
#         "total_revenue": 3800,
#         "products": ["Laptop", "Smartphone"]
#     },
#     "Apparel": {
#         "total_revenue": 450,
#         "products": ["Jeans", "T-Shirt"]
#     },
#     "Media": {
#         "total_revenue": 60,
#         "products": ["Book"]
#     }
# }

transactions=(
    {"product": "Laptop", "category": "Electronics", "price": 1000, "quantity": 2},
    {"product": "Jeans", "category": "Apparel", "price": 50, "quantity": 5},
    {"product": "Smartphone", "category": "Electronics", "price": 800, "quantity": 1},  
    {"product": "T-Shirt", "category": "Apparel", "price": 20, "quantity": 10},
    {"product": "Laptop", "category": "Electronics", "price": 1000, "quantity": 1},
    {"product": "Book", "category": "Media", "price": 15, "quantity": 4}
)

def aggregate_sales(transactions):
    result= {}

    for item in transactions:
        product= item["product"]
        category= item["category"]
        price= item["price"]
        quantity= item["quantity"]

        revenue= price*quantity

        if category not in result:
            result[category]= {
                "total_revenue": 0,
                "product": []
            }

            result[category]["total_revenue"] += revenue

        if product not in result[category]["product"]:
            result[category]["product"].append(product)

    return result
            

didi= aggregate_sales(transactions)
print(didi)



